# Generated by Django 5.0.4 on 2024-04-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_store_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pant_list',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sore_list', to='clothes.store_list'),
        ),
    ]
